- broad-wb-malkov.json
- profiles/thurloe-sa/terraform/thurloe/sa.tf
- profiles/thurloe-sa/terraform/thurloe/variables.tf.ctmpl
- profiles/thurloe/terraform/thurloe/api-services.tf
- profiles/thurloe/terraform/thurloe/thurloe.tf
- profiles/thurloe/terraform/thurloe/variables.tf.ctmpl
Added required permissions and infrastructure to pull Thurloe configuration from a Google bucket.
> Thurloe app configuration

- profiles/opendj-sa/terraform/opendj/sa.tf
- profiles/opendj-sa/terraform/opendj/variables.tf.ctmpl
- profiles/opendj/terraform/opendj/api-services.tf
- profiles/opendj/terraform/opendj/opendj.tf
- profiles/opendj/terraform/opendj/variables.tf.ctmpl
- Add OpenDJ profile
- Add OpenDJ SA profile
> PERF-139: OpenDJ Profile

- broad-wb-malkov.json
- broad-wb-perf2.json
- broad-wb-rluckom.json
- profiles/opendj-configs/terraform/opendj/config.tf
- profiles/opendj-configs/terraform/opendj/variables.tf.ctmpl
- Added OpenDJ config render profile
> PERF-139 OpenDJ config render profile

- broad-wb-malkov.json
- broad-wb-perf2.json
- broad-wb-rluckom.json
- profiles/sam/terraform/sam/dns_sa.json.ctmpl
- profiles/sam/terraform/sam/sam.tf
- profiles/sam/terraform/sam/variables.tf.ctmpl
- profiles/thurloe/terraform/thurloe/dns.tf
- profiles/thurloe/terraform/thurloe/thurloe.tf
- profiles/thurloe/terraform/thurloe/variables.tf.ctmpl
- profiles/thurloe/terraform/thurloe/vault.tf
Extract load-balanced-instances in sam & Thurloe into a tf module
> Rl modularize services

- broad-wb-malkov.json
- broad-wb-perf2.json
- broad-wb-rluckom.json
- profiles/agora/terraform/agora/dns.tf
- profiles/agora/terraform/agora/dns_sa.json.ctmpl
- profiles/leonardo/terraform/leonardo/dns.tf
- profiles/leonardo/terraform/leonardo/dns_sa.json.ctmpl
- profiles/sam/terraform/sam/dns.tf
- profiles/sam/terraform/sam/dns_sa.json.ctmpl
- profiles/thurloe/terraform/thurloe/dns.tf
- profiles/thurloe/terraform/thurloe/dns_sa.json.ctmpl
More cleanup, this time targeting making sure providers are in json
> standardize on tf sas in json

- profiles/cromiam-sa/terraform/cromiam/variables.tf.ctmpl
- profiles/job-manager-sa/terraform/job-manager/variables.tf.ctmpl
- terra-alpha.json
- terra-dev.json
- terra-prod.json
- terra-qa.json
sql client role for jm and cromiam
> sql client role for jm and cromiam

- profiles/leonardo-pubsub/terraform/leonardo/pubsub.tf
- profiles/leonardo-pubsub/terraform/leonardo/variables.tf.ctmpl
- profiles/vm-image-sa/terraform/vm-image-sa/variables.tf.ctmpl
- terra-dev.json
- terra-perf.json
- terra-prod.json
- terra-qa.json
- terra-staging.json
https://broadworkbench.atlassian.net/browse/IA-1542
For applying profiles, do something like `./dsp-k8s-deploy/application-deploy.sh -j terra-<evn>.json -p leonardo-pubsub`
`dsp-k8s-deploy` changes are just to bring up the folder up-to-date
> IA-1542 Add pubsub queue for leonardo

- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/perimeters.tf
- terra-prod.json
> Add new ingress bridges to Terra prod

- terra-dev.json
- terra-perf.json
- terra-prod.json
https://broadworkbench.atlassian.net/browse/CA-636
> CA-636 add rawls SA

- profiles/leonardo-pubsub/terraform/leonardo/variables.tf.ctmpl
> [IA-1512] update leo-pubsub permissions

- profiles/terra-kernel-k8s/manual_steps.py
- profiles/terra-kernel-k8s/terraform/terra-kernel-k8s/api-services.tf
- profiles/terra-kernel-k8s/terraform/terra-kernel-k8s/k8s.tf
- profiles/terra-kernel-k8s/terraform/terra-kernel-k8s/nat.tf
- profiles/terra-kernel-k8s/terraform/terra-kernel-k8s/network.tf
- profiles/terra-kernel-k8s/terraform/terra-kernel-k8s/outputs.tf
- profiles/terra-kernel-k8s/terraform/terra-kernel-k8s/variables.tf.ctmpl
- terra-kernel-k8s.json
Current profile creates cluster and includes manual instructions for installing Istio.
Further cluster configuration will be done in Helm.
> DDO-41 create kernel k8s cluster

- terra-prod.json
Follow-up PRs will apply this change in perf/stable/prod. QA'ing this in staging first. Will need this change to be applied, since I don't have permission to do so.
https://precisionmedicineinitiative.atlassian.net/browse/RW-4339
Please merge when ready to apply this change.
> Enable GCS exfil enforcement in AoU staging

- terra-perf.json
- terra-prod.json
https://precisionmedicineinitiative.atlassian.net/browse/RW-4339
perf, stable, and prod
Please merge and apply when ready.
> Enforce GCS exfil prevention in all AoU environments

- terra-prod.json
Permissions should now be correctly configured.
> Enable AoU log sinks in terra prod

- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/create-sam-perimeter-resource.sh
- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/get_access_token.py
- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/perimeters.tf
- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/variables.tf.ctmpl
- terra-dev.json
- terra-perf.json
- terra-prod.json
https://broadworkbench.atlassian.net/browse/CA-668
Have not tried running it.
After this is merged we can delete the original script: https://github.com/broadinstitute/firecloud-develop/blob/dev/run-context/live/scripts/service-perimeters/create-service-perimeter.sh
> [CA-668] Adding Sam service perimeter resource creation to Terraform

- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/log-sinks.tf
🤦 - messed this up with the initial implementation. Just now realized these two sinks haven't been flowing properly. I will also need this applied in all environments. @gmalkov do you have bandwidth to help apply this?
> Fix VPC-SC folder log sink writers for dataproc / cloud storage

- scripts/project-setup-scripts/add-folder-roles-for-service-accounts-and-terra-billing-and-test-users.sh
- scripts/project-setup-scripts/create-custom-iam-roles-for-projects.sh
https://broadworkbench.atlassian.net/browse/CA-1194
> [CA-1194] add prod and QA rbs folder to setup script and set up SA access

- scripts/project-setup-scripts/add-folder-roles-for-service-accounts-and-terra-billing-and-test-users.sh
https://broadworkbench.atlassian.net/browse/CA-1314
> grant project mover role to terra-billing

- scripts/project-setup-scripts/terra-billing-project-owner.yaml
https://broadworkbench.atlassian.net/browse/CA-1620
> Adding serviceusage.quotas.get permission 

- scripts/project-setup-scripts/terra-billing-project-owner.yaml
- scripts/project-setup-scripts/update-custom-iam-roles-for-projects.sh
This change adds the resourcemanager.projects.getIamPolicy to billing project owners. I have not run the script to make the change or verified that it won't duplicate yet (and won't need to change), but wanted to hold off until I had PR approval before figuring it out.
> [CA-1318] Add the permission to terraform role definition
