- README.md
- profiles/sam-sa/terraform/sam/sa.tf
- profiles/sam-sa/terraform/sam/variables.tf.ctmpl
- profiles/sam/terraform/sam/api-services.tf
- profiles/sam/terraform/sam/sam.tf
- profiles/sam/terraform/sam/variables.tf.ctmpl
- profiles/thurloe/terraform/thurloe/thurloe.tf
Terraform profiles for Sam and the Sam SA. Based off the Thurloe profiles.
There is a lot of copy-paste boilerplate in `variables.tf` between Sam and Thurloe; in Slack discussion I'd like to push that off for a future PR/refactor.
To get this working in `broad-wb-perf2` from scratch, I had to:
* set up kubectl locally by following kubernetes.md
* manually enable Cloud DNS via Cloud Console
* apply the `dns` profile
* apply the `ssl` profile
* apply the `network` profile
* apply the `sam-sa`  profile (which I ran normally, not with ADC, i.e. without `-a`)
* apply the `sam` profile
would it be better to add `dns`, `ssl`, `network`, `sam-sa` as dependencies somewhere in the `sam` profile? Is this possible?
> Sam profile

- profiles/sam/terraform/sam/sam.tf
- profiles/sam/terraform/sam/variables.tf.ctmpl
- allow for multiple Sam instances in the load balancer group
- DNS entries for each of the instances
> support for multiple Sam instances

- broad-wb-malkov.json
- broad-wb-perf2.json
- broad-wb-rluckom.json
- containers/ruby-consul-terraform/render_configs.rb
- profiles/populate-vault/terraform/populate-vault/common.tf
- profiles/populate-vault/terraform/populate-vault/variables.tf.ctmpl
- profiles/populate-vault/terraform/populate-vault/vault.tf
- profiles/thurloe-configs/terraform/thurloe/config.tf
- profiles/thurloe-configs/terraform/thurloe/variables.tf.ctmpl
- profiles/thurloe/terraform/thurloe/dns.tf
- profiles/thurloe/terraform/thurloe/dns_sa.json.ctmpl
- profiles/thurloe/terraform/thurloe/thurloe.tf
- profiles/thurloe/terraform/thurloe/variables.tf.ctmpl
- profiles/thurloe/terraform/thurloe/vault.tf
This proposes a way of populating Vault with secrets from two sources:
1) The created terraform environment
2) Existing Vault secrets (copying)
The goal here is that over time, more secrets will come from #1 and fewer from #2. Copying exists so that we can use values manually populated in Vault when we create ephemeral environments, and still let the configs for each environment get populated from an environment-specific vault path prefix (see https://github.com/broadinstitute/firecloud-develop/pull/1698).
This approach has security implications. Specifically, secrets read or populated with terraform are stored in the terraform state file in cleartext (https://www.terraform.io/docs/providers/vault/index.html). This could be helpful since it allows terraform to keep the values for an …
> Rl populate vault

- broad-wb-rluckom.json
- profiles/opendj-configs/terraform/opendj/variables.tf.ctmpl
- profiles/populate-vault/terraform/populate-vault/common.tf
- profiles/populate-vault/terraform/populate-vault/thurloe.tf
- profiles/populate-vault/terraform/populate-vault/variables.tf.ctmpl
- profiles/ssl/terraform/ssl/terra-env-wildcard-ssl-certificate-black.crt.ctmpl
- profiles/ssl/terraform/ssl/terra-env-wildcard-ssl-certificate-black.key.ctmpl
- profiles/ssl/terraform/ssl/terra-env-wildcard-ssl-certificate-red.crt.ctmpl
- profiles/ssl/terraform/ssl/terra-env-wildcard-ssl-certificate-red.key.ctmpl
- profiles/thurloe-configs/terraform/thurloe/config.tf
- profiles/thurloe-configs/terraform/thurloe/variables.tf.ctmpl
- profiles/thurloe-sa/terraform/thurloe/sa.tf
- profiles/thurloe-sa/terraform/thurloe/variables.tf.ctmpl
- profiles/thurloe/terraform/thurloe/dns.tf
- profiles/thurloe/terraform/thurloe/thurloe.tf
- profiles/thurloe/terraform/thurloe/variables.tf.ctmpl
- profiles/thurloe/terraform/thurloe/vault.tf
This PR works with https://github.com/broadinstitute/firecloud-develop/pull/1698 to update the values that ephemeral Thurloes get configured with. It allows Thurloe to start up configured with its ephemeral database, service account, and other resources.
> Rl vault config render vals

- broad-wb-malkov.json
- broad-wb-perf2.json
- broad-wb-rluckom.json
- containers/ruby-consul-terraform/render_configs.rb
- profiles/thurloe-configs/terraform/thurloe/config.tf
- profiles/thurloe-configs/terraform/thurloe/variables.tf.ctmpl
This uses https://github.com/broadinstitute/dsp-k8s-deploy/pull/27 to add configurable consul logging to the Thurloe template rendering step. 
I'm not adding this in sam and opendj in this PR because there's an open PR for thoseand I don't want to cause conflicts.
> set consul-template log level and retry attempts

- profiles/vm-image-sa/terraform/vm-image-sa/sa.tf
- profiles/vm-image-sa/terraform/vm-image-sa/variables.tf.ctmpl
the script needs these permissions as it tries to create an instance with a service account for testing the custom image
```
ERROR: (gcloud.compute.instances.create) Could not fetch resource:
- The user does not have access to service account '1028065715937-compute@developer.gserviceaccount.com'.  User: 'image-build-account@broad-dsp-gcr-public.iam.gserviceaccount.com'.  Ask a project owner to grant you the iam.serviceAccountUser role on the service account
```
> Permissions update

- profiles/vm-image-sa/terraform/vm-image-sa/variables.tf.ctmpl
This permission is needed as the script creates a custom dataproc image, which it then uses to spin up a dataproc cluster for testing purposes.
> adding permission needed for smoke test

- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/ingress-bridges.tf
- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/perimeters.tf
- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/variables.tf.ctmpl
- terra-rawls-vpc-dev.json
For ease of management, this effort requires that we instantiate multiple perimeters with a single profile environment, to match the logical ownership of one rawls server environment to a set of associated perimeter configurations. To achieve this required some gymnastics in the profile templating tools to allow for more complex input types - here arbitrary JSON is supported.
Idea:
- copy or mount the profile.json file onto the rendering docker image 
- Define arbitrary "extras" section in a given profile configuration
- Read this directly in consul template, pull out arbitrary structured JSON values
TODO: volume mounting, other environments, complete environment config, test e2e with rendering
Current testing approach for the consul rendering:
```
docker run -v …
```
> Add Rawls VPC-SC Terraform profile

- terra-rawls-vpc-dev.json
- terra-rawls-vpc-perf.json
- terra-rawls-vpc-prod.json
If correctly imported, this should produce 0 diffs.
Related issues:
1. placeholder accessLevels are defined across other Terra envs (alpha, staging, qa), but appear to be unused. I don't know whether it's worth porting those into this repo before they are used: https://github.com/broadinstitute/firecloud-develop/tree/dev/run-context/live/scripts/service-perimeters/access-levels/alpha
2. There is some additional scripting in firecloud-devop for initializing a perimeter in Sam. This will need to be ported into the new approach somehow.
New perimeters/bridges are separated out into this PR: https://github.com/calbach/terraform-terra/pull/1
@gpolumbo-broad @RLuckom
> Bring in all existing perimeters

- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/perimeters.tf
This eliminates one of the key caveats of the Terraform setup: You can now apply changes to the restricted services list via a normal Terraform update.
Per my old comment here, turns out this wasn't an issue with the Terraform provider; I just didn't have the right syntax. I was educated here: https://github.com/terraform-providers/terraform-provider-google/issues/4509 . Previously, this filter ignored the whole `status` field, which unnecessarily included `restricted_services` and `access_levels` - this meant you could only use Terraform for the initial creation but not subsequent updates to set these particular fields.
> Use a more specific ignore_changes filter on perimeters

- terra-dev.json
No action required - I've already applied this update in dev with my test Firecloud admin account:
```
gcloud access-context-manager perimeters update accessPolicies/228353087260/servicePerimeters/terra_dev_aou_test --add-restricted-services=storage.googleapis.com
```
~~Note: manual gcloud commands are necessary to update this on account of https://github.com/terraform-providers/terraform-provider-google/issues/4509~~
**Update**: https://github.com/broadinstitute/terraform-terra/pull/117 fixes this so the change can be applied with a normal terraform apply.
Expect follow-up PR(s) next week to apply a similar change in the other environments (I will need help applying those).
> Enable AoU GCS exfiltration enforcement in dev

- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/perimeters.tf
- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/variables.tf.ctmpl
- terra-dev.json
- terra-perf.json
- terra-prod.json
https://broadworkbench.atlassian.net/browse/CA-688
https://broadworkbench.atlassian.net/browse/DDO-111
- Adds a new optional `folder_admins` parameter to a perimeter config, which grants IAM roles on the folder corresponding to a Rawls perimeter
- Functional change: adds the Monitoring Viewer role per CA-688. All other bindings should already exist.
- The folder IAM may need to be imported before this is applied, to verify there are no extra bindings which might be removed by this.
If there are extra IAM bindings that need to be maintained, but which we don't want to manage via this Terraform config, I can change the Terraform to be non-destructive.
Note: I don't have access to render this template or fully execute terraform plan. I used the following command to at least test the …
> Add IAM admin policies for AoU Rawls folders

- terra-prod.json
https://precisionmedicineinitiative.atlassian.net/browse/RW-4431
Background: we sent out communications to ask folks to clone / upgrade their older workspaces before we deleted them all, some of these predate the perimeter and are therefore outside. Cloning now understandably fails when attempting to copy workspace notebooks into the perimeter.
Plan is revert GCS enforcement for a week while we give folks a chance to clone, then re-enable.
> Temporarily revert GCS enforcement in AoU prod

- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/perimeters.tf
- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/variables.tf.ctmpl
- terra-dev.json
- terra-perf.json
- terra-prod.json
Reverts broadinstitute/terraform-terra#124
This currently cannot be applied due to insufficient roles for the Terraform SA - revert for now so that master reflects the current state of the world:
```
google_folder_iam_policy.folder-admin-policy["terra_prod_aou_stable"]: Creating...
Error: Error setting IAM policy for folder "folders/300547813290": googleapi: Error 403: The caller does not have permission, forbidden
on perimeters.tf line 25, in resource "google_folder_iam_policy" "folder-admin-policy":
25: resource "google_folder_iam_policy" "folder-admin-policy" {
Error: Error setting IAM policy for folder "folders/727685043294": googleapi: Error 403: The caller does not have permission, forbidden
on perimeters.tf line 25, in resource "google_folder_iam_policy" "folder-admin-policy":
25: …
```
> Revert "Add IAM admin policies for AoU Rawls folders"

- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/ingress-bridges.tf
- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/perimeters.tf
- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/variables.tf.ctmpl
- terra-prod.json
Projects must belong to perimeters before a bridge is created. Therefore, for TF initialization we need to ensure that the CDR project gets included in the initial VPC-SC perimeter (Rawls will handle keeping it in there after creation).
> Include CDR in initial VPC-SC perimeter, add preprod

- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/perimeters.tf
- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/variables.tf.ctmpl
- terra-dev.json
- terra-perf.json
- terra-prod.json
Reverts broadinstitute/terraform-terra#127
Prerequisite: Terraform SA needs the "Folder IAM Admin" role, either at the org level or for each of the above folders.
Please confirm this applies before merging.
CC @dvoet @gpolumbo-broad
> Unrevert: Add IAM admin policies for AoU Rawls folders

- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/log-sinks.tf
- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/variables.tf.ctmpl
- terra-dev.json
- terra-perf.json
- terra-prod.json
https://broadworkbench.atlassian.net/browse/DDO-121
Design: https://docs.google.com/document/d/1gzMuZSFOgFa_usCtPHWzGdwEcfexQN70Q6uI4sy5n-E/edit
- Creates BigQuery sink datasets in target project
- Creates aggregated log sinks on the perimeter folder
- Enables log sinks for dev/perf AoU perimeters (prod to follow)
- Currently grabs:
- Dataproc (Leo-related VM logs)
- GCS access logs
- BQ access logs
Applying this will require the following access (ideally on the terraform SA):
- roles/logging.configWriter (Logs Configuration Writer) on respective perimeter folders
- ~~roles/bigquery.dataOwner (BigQuery Data Owner) on audit sink projects.~~ Granted
CC @dvoet @gpolumbo-broad
> Add aggregated perimeter log sinks

- terra-prod.json
https://precisionmedicineinitiative.atlassian.net/browse/RW-4432
Our temporary issue has now been mitigated. This reverts https://github.com/broadinstitute/terraform-terra/pull/126
> Re-enable GCS enforcement in AoU prod

- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/log-sinks.tf
- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/variables.tf.ctmpl
Problems:
- The only supported mechanism for managing BigQuery ACLs is an all-or-nothing list of `access` clauses.
- As a side-effect of having created the BigQuery sink, the Terraform user itself is  an owner.
- dataEditor gets turned into EDITOR by the BigQuery API, which looks like a delta as well
Here, I pick out the SA name from the incoming SA creds file to determine the active Terraform SA name, then attach that to the BigQuery dataset. If this worked, it *should* result in no changes to the current ACLs.
Process follow-up:
As part of applying a Terraform change, there should probably be a follow-up step to run `terraform plan` to determine whether there are unexpected changes.
> Fix for BQ dataset ACLs on perimeter log sinks

- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/log-sinks.tf
Expand/rename this dataset to encompass both dataproc and GCE logs. AoU is adding support for Leo GCE runtimes, in addition to Dataproc, hence the change.
I'm not sure exactly how the switch over will occur here and what changes Terraform will attempt to apply. We *do not* want to delete the old BigQuery dataset as part of this change. We *may* delete the old log sink configuration, assuming the new version subsumes the old. Later I may try to merge the two datasets and the delete the old dataset manually.
CC @rtitle @Qi77Qi @dvoet
> Include GCE logs in Terra audit log sinks

- terra-dev.json
We will eventually need to add a second service perimeter and folder to all AoU environments, as part of our Controlled Tier access restrictions.  This PR adds one to AoU Test so we can prototype.  Similar to PRs #130 and #131.
Note: project naming patterns do not match exactly.  This is OK for the prototype.
> Add Service Perimeter terra_dev_aou_test_2

- profiles/rawls-service-perimeters/terraform/rawls-service-perimeters/perimeters.tf
- terra-dev.json
[Design doc](https://docs.google.com/document/d/1IeHVZt7N2q_kMDFhUAYBOLFzf8fHNu8LgjSGtPIVUAg/edit?ts=5ff5ef06#). The end goal here is to support dynamic genomic cohort extraction implemented on the backend by Cromwell.
- Add BigQuery job user and read session roles, to allow the extraction SA to take BigQuery actions which are billed against researcher projects.
- Add the RW extraction pet SA to the admin / access level, in order to permit backend Cromwell execution from outside the perimeter (Cromwell does not support execution within VPC-SC currently).
- The new extraction SA is added in test/dev only. Other environments will follow later.
> [RW-6285] VPC-SC changes to support genomics cohort extraction

- .gitignore
- scripts/project-setup-scripts/add-folder-roles-for-service-accounts-and-terra-billing-and-test-users.sh
- scripts/project-setup-scripts/rawls-sa-condition-file.yaml
https://broadworkbench.atlassian.net/browse/CA-1370
Adds permission required to set policies on google projects from the Buffer service
> [CA-1370] add projectIamAdmin role to rawls SA

- scripts/project-setup-scripts/add-folder-roles-for-service-accounts-and-terra-billing-and-test-users.sh
- scripts/project-setup-scripts/rawls-sa-condition-file.yaml
followup to: https://github.com/broadinstitute/terraform-terra/pull/152
fixes an issue where now all new policy bindings need to specify a condition, even if it is `None`
the issue was that if any existing iam policy has a condition, then all new policy updates require a condition as well.
```
+ gcloud resource-manager folders add-iam-policy-binding 599966635789 --member=group:firecloud-project-owners@test.firecloud.org --role=roles/owner
[1] EXPRESSION=api.getAttribute('iam.googleapis.com/modifiedGrantsByRole',[]).hasOnly( ['roles/terra_billing_project_owner','roles/terra_workspace_can_compute','roles/terraBucketReader','roles/terraBucketWriter']), TITLE=only_custom_roles, DESCRIPTION=Only allow adding specified custom iam roles to projects in this folder.
[2] None
[3] Specify a new …
```
> [CA-1370] add condition on all policy bindings

- scripts/project-setup-scripts/rawls-sa-condition-file.yaml
we found that there were some permission issues when updating the iam on QA fiab runs.
On a hunch, I tried removing the conditional statement in the console. After that, the test passed.
The conditional apparently didn't matter on the dev fiab, but with this change, QA fiabs (and other envs) should be unblocked.
I removed `roles/` after seeing this:
```
✗ gcloud iam roles describe roles/terra_billing_project_owner --organization=400176686919
ERROR: (gcloud.iam.roles.describe) Invalid value for [ROLE_ID]: The role id that starts with 'roles/' only stands for curated role. Should not specify the project or organization for curated roles
✗ gcloud iam roles describe terra_billing_project_owner --organization=206744735509
description: permissions for billing project owners
etag: BwW-YwwBLIs= …
```
> [CA-1435] fix role name in conditional

- scripts/project-setup-scripts/add-folder-roles-for-service-accounts-and-terra-billing-and-test-users.sh
https://broadworkbench.atlassian.net/browse/CA-1443
I'm not sure why there was separate logic for QA and prod envs, but projects on prod should be administered by the admin group (`firecloud-project-owners@${APPS_DOMAIN}`) and I think it's ok if the QA env is administered only by the qa.fc.o admin group and not the test.fc.o admin group.
---
verifying that qa fiabs still work ok with this change (after removing the test.fc.o admin group and test.fc.o billing group from the qa folder) in this job: https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/51739/
kicked off a new run because of a flaky orch/gpalloc failure in the previous run
https://fc-jenkins.dsp-techops.broadinstitute.org/job/swatomation-pipeline/51745/
> [CA-1443] add fcprojectowners (admin group) to prod, remove extraneous groups on qa folder

- scripts/project-setup-scripts/terra-billing-project-owner.yaml
- scripts/project-setup-scripts/terra-workspace-can-compute.yaml
- scripts/project-setup-scripts/update-custom-iam-roles-for-projects.sh
Per Google Support, there are additional permissions needed to be able to view Quota information in the Console UI vs. `gcloud`.  (Google said they will update the documentation)
Additionally, I made a view minor ease of use updates to the `update-custom-iam-roles-for-projects.sh` to make it so that calling the script with no arguments will show usage, and so that commands are not echoed in order to make it easier to parse the output from the commands.  
And finally, instead of alpha sorting the permissions, I have added some comments to explaining why the permissions are needed and what they are used for.  I propose that we keep this up going forward for all permissions in both role definitions.
> CA-1620 undocumented permissions to view Quota
